[[entries]]
path = ["misc", "new.ycombinator.com"]
tags = ["hacker", "news", "social", "ycombinator"]
obfuscated_path = ["lj01g7OD8g30F6X9"]

[[entries]]
path = ["misc", "www.facebook.com"]
tags = ["facebook", "social"]
obfuscated_path = ["lj01g7OD8g30F6X9"]

[[entries]]
path = ["misc", "mail.protonmail.com"]
tags = ["mail", "protonmail", "social"]
obfuscated_path = ["lj01g7OD8g30F6X9"]

[[entries]]
path = ["work", "mona", "design.md"]
tags = []
obfuscated_path = ["lj01g7OD8g30F6X9"]
